### ISSUE TITLE
rocket helm

### ISSUE THREAD

**Issue by samrogueRW** [RetroWoW/PTR#74]
**Description**:
Goblin Rocket Helmet not working as intended 

**Current behavior**: Tell us what happens
it only stuns the target for 10 sec instead of the 30
**Expected behavior**: Tell us what should happen instead
it should always be a 30 sec CC unless u get heartbreak wich is 1% chance to happen
**Steps to reproduce the problem**:

1. just change the DR from 10 sec to 30 cus everytime i use it it is 10 sec 
2. 
3. 
NOTE: i didn't use any kind of CC that might change the DR before using it
**Source:** 
item info says it

**Comment by mentos987** [comment]
30sec might be much. But 10sec is too little when you consider the long cd and that you probably have to waste the item slot on a shitty item for several fights. Also, you can dispel it. 

I'd rather have 30s than 10s.

One thing that could use a change is the duration of mind control (a min?) that is way too long.

**Comment by Bam27** [comment]
Please include a valid source. Youtube video, or patch notes stating how this item worked in PVP.

**Comment by Bam27** [comment]
https://wow.gamepedia.com/Patch_1.11.0   (ctrl + f + rocket) 

"A player is now much more likely to break out of the The Reckless Charge effect of the Rocket Helmet early. This is to maintain consistency with all other effects that take control away from a player (Sheep, Stun, Hibernate, etc...). This change only affects players, there is no change in using it against monsters."

In order to fix to this standard, a custom heartbeat sensor (which is not 1% and is the combination of different variables, including spell hit%) would need to be applied with an ever increasing chance to break on every second after 6 seconds of application.
